# Generated by Django 4.2 on 2023-05-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_disco_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='artista',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disco',
            name='stock',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='disco',
            name='vendidos',
            field=models.FloatField(default=0),
        ),
    ]
