# Generated by Django 4.2 on 2023-05-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_disco_artista_disco_stock_disco_vendidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='artista',
            field=models.CharField(default='Sin artista', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disco',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='disco',
            name='vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
