# Generated by Django 4.2 on 2023-05-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_disco_artista_alter_disco_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='artista',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
