# Generated by Django 4.2 on 2023-05-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_disco_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='vendidos',
            field=models.IntegerField(default=1),
        ),
    ]
