# Generated by Django 4.2 on 2023-05-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_disco_vendidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
