# Generated by Django 4.2.1 on 2023-05-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_disco_vendidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
